// app/api/firebase-messaging-sw/route.ts
// Serves the Firebase Messaging Service Worker with the Firebase config
// injected at request time so we never commit credentials to source control.
import { NextResponse } from 'next/server';

export const runtime = 'nodejs';

export async function GET() {
  const config = {
    apiKey:            process.env.NEXT_PUBLIC_FIREBASE_API_KEY            ?? '',
    authDomain:        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN        ?? '',
    projectId:         process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID         ?? '',
    storageBucket:     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET     ?? '',
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? '',
    appId:             process.env.NEXT_PUBLIC_FIREBASE_APP_ID             ?? '',
  };

  const swContent = `
// ── MyOrbit — Firebase Messaging Service Worker ────────────────────────────
// Auto-generated by /api/firebase-messaging-sw — do not edit directly.
importScripts('https://www.gstatic.com/firebasejs/10.7.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.7.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

// ── Background message handler ─────────────────────────────────────────────
// Fires when a push arrives and the app tab is closed or in the background.
messaging.onBackgroundMessage(function(payload) {
  console.log('[MyOrbit SW] Background message received:', payload);

  const notification = payload.notification || {};
  const data         = payload.data         || {};

  const title = notification.title || data.title || 'MyOrbit';
  const body  = notification.body  || data.body  || '';
  const icon  = notification.icon  || '/icons/icon-192.png';
  const badge = '/icons/icon-72.png';
  const url   = data.url || '/orbit/tasks';

  self.registration.showNotification(title, {
    body,
    icon,
    badge,
    data:            { url },
    tag:             data.tag || 'myorbit',
    renotify:        true,
    requireInteraction: false,
  });
});

// ── Notification click ─────────────────────────────────────────────────────
self.addEventListener('notificationclick', function(event) {
  event.notification.close();

  const url = (event.notification.data && event.notification.data.url)
    ? event.notification.data.url
    : '/orbit/tasks';

  event.waitUntil(
    clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function(windowClients) {
        // Focus an existing tab if one is open
        for (const client of windowClients) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.focus();
            client.navigate(url);
            return;
          }
        }
        // Otherwise open a new tab
        if (clients.openWindow) return clients.openWindow(url);
      })
  );
});
`;

  return new NextResponse(swContent, {
    headers: {
      'Content-Type':        'application/javascript; charset=utf-8',
      'Service-Worker-Allowed': '/',
      'Cache-Control':       'no-store, no-cache',
    },
  });
}
