// app/api/auth/reset-password/route.ts
// Consumes a password reset token and sets the new password.
// Token was generated by /api/auth/forgot-password and stored as `reset_<token>`
// in the Session table with a 1-hour expiry.

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import bcrypt from 'bcryptjs';

export const runtime = 'nodejs';

export async function POST(req: NextRequest) {
  try {
    const { token, password } = await req.json();

    // ── Validate inputs ─────────────────────────────────────────────────────
    if (!token || typeof token !== 'string') {
      return NextResponse.json({ error: 'Invalid or missing token.' }, { status: 400 });
    }
    if (!password || typeof password !== 'string' || password.length < 8) {
      return NextResponse.json(
        { error: 'Password must be at least 8 characters.' },
        { status: 400 }
      );
    }

    // ── Look up the reset session record ────────────────────────────────────
    const sessionRecord = await prisma.session.findUnique({
      where: { token: `reset_${token}` },
      include: { user: true },
    });

    if (!sessionRecord) {
      return NextResponse.json(
        { error: 'This reset link is invalid or has already been used.' },
        { status: 400 }
      );
    }

    // ── Check expiry ────────────────────────────────────────────────────────
    if (new Date() > sessionRecord.expiresAt) {
      // Clean up expired token
      await prisma.session.delete({ where: { id: sessionRecord.id } }).catch(() => {});
      return NextResponse.json(
        { error: 'This reset link has expired. Please request a new one.' },
        { status: 400 }
      );
    }

    // ── Hash the new password ────────────────────────────────────────────────
    const passwordHash = await bcrypt.hash(password, 12);

    // ── Update user password + delete the used reset token atomically ────────
    await prisma.$transaction([
      prisma.user.update({
        where: { id: sessionRecord.userId },
        data: { passwordHash },
      }),
      prisma.session.delete({
        where: { id: sessionRecord.id },
      }),
    ]);

    return NextResponse.json({ ok: true });
  } catch (e: any) {
    console.error('Reset password error:', e);
    return NextResponse.json({ error: 'Server error. Please try again.' }, { status: 500 });
  }
}
